# ICC 2022 - Docker Basics Workshop - Part II, Docker Compose
# ref: https://github.com/compose-spec/compose-spec/blob/master/spec.md
---
services:
  gateway:
    image: inductiveautomation/ignition:8.1.19
    hostname: gateway
    ports:
      - 9088:8088
    environment:
      IGNITION_EDITION: standard
      # GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-admin-password
      ACCEPT_IGNITION_EULA: "Y"
    networks:
      - default
      - db
    volumes:
      - gateway-data:/usr/local/bin/ignition/data
      - ./gw-init/gateway.gwbk:/restore.gwbk
    secrets:
      - gateway-admin-password
    command: >
      -n Ignition-pt2
      -r /restore.gwbk

  edge:
    image: inductiveautomation/ignition:8.1.19
    hostname: edge
    ports:
      - 9089:8088
    environment:
      IGNITION_EDITION: edge
      # GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-admin-password
      ACCEPT_IGNITION_EULA: "Y"
      GATEWAY_NETWORK_0_HOST: gateway
      EAM_SETUP_INSTALLSELECTION: Agent
      EAM_AGENT_CONTROLLERSERVERNAME: Ignition-pt2
      GATEWAY_MODULES_ENABLED: enterprise-administration,modbus-driver-v2,opc-ua,perspective,tag-historian
    volumes:
      - edge-data:/usr/local/bin/ignition/data
      - ./gw-init/edge-uuid.txt:/usr/local/bin/ignition/data/.uuid
      - ./gw-init/edge-metro-keystore:/usr/local/bin/ignition/data/local/metro-keystore
      - ./gw-init/edge.gwbk:/restore.gwbk
    secrets:
      - gateway-admin-password
    command: >
      -n Ignition-edge-pt2
      -r /restore.gwbk

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER: ignition
      POSTGRES_DB: ignition
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    secrets:
      - postgres-password
    networks:
      db:
        aliases:
          - db
    
  pgadmin:
    image: dpage/pgadmin4:6.14
    ports:
      - 9090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin-password
      PGADMIN_DISABLE_POSTFIX: true
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./db-init/servers.json:/pgadmin4/servers.json
    networks:
      - db
    secrets:
      - pgadmin-password
    
secrets:
  postgres-password:
    file: ./secrets/POSTGRES_PASSWORD
  pgadmin-password:
    file: ./secrets/PGADMIN_PASSWORD
  gateway-admin-password:
    file: ./secrets/GATEWAY_ADMIN_PASSWORD

networks:
  default:
  db:

volumes:
  gateway-data:
  edge-data:
  db-data:
  pgadmin-data:
